# ---- Second Stage: runtime ----
FROM mcr.microsoft.com/dotnet/aspnet:7.0.5-alpine3.17

# specify working directory
WORKDIR /app

# copy the published app
COPY . .

# expose the port
EXPOSE 10000
ENV ASPNETCORE_URLS=http://+:10000/
ENV Observability__JaegerUrl=
ENV ReverseProxy__QuestionsAppUrl=

# run the application
ENTRYPOINT ["dotnet", "ReverseProxy.dll"]