version: '3.8'

secrets:
  db_password:
    file: ./docker-postgres-password.txt

services:
  jaeger:
    image: jaegertracing/all-in-one:1.46
    container_name: jaeger-container
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - "COLLECTOR_ZIPKIN_HOST_PORT=:9411"
  # Database server
  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    container_name: postgres-container
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data    
    ports:
      - 5432:5432
    secrets:
      - db_password
    environment:
      - POSTGRES_USER=devops-example
      - POSTGRES_DB=devops-example-db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
