# ---- Second Stage: runtime ----
FROM mcr.microsoft.com/dotnet/aspnet:7.0.5-alpine3.17

# specify working directory
WORKDIR /app

# copy the published app
COPY . .

# expose the port
EXPOSE 10000
ENV ASPNETCORE_URLS=http://+:10000/

# Set config using env variables
ENV Observability__JaegerUrl=
ENV DB__Host=
ENV DB__Database=devops-example-db
ENV DB__UserName=devops-example
ENV DB__Password=devops-example

# run the application
ENTRYPOINT ["dotnet", "QuestionsApp.Web.dll"]